import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f8fafc", padding: 20 },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
    marginTop: 40,
  },
  backText: { color: "#64748b", fontSize: 16, marginLeft: 8 },
  card: {
    backgroundColor: "#fff",
    borderRadius: 24,
    padding: 24,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    elevation: 5,
  },
  supportContainer: {
    backgroundColor: "#f1f5f9",
    padding: 15,
    borderRadius: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  supportLabel: { fontWeight: "700", color: "#1e293b" },
  imagePlaceholder: {
    height: 180,
    backgroundColor: "#fff",
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    overflow: "hidden",
  },
  questionText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1e293b",
    marginBottom: 20,
  },

  // Opções
  optionsList: { gap: 10 },
  optionItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  optionSelected: { borderColor: "#3b82f6", backgroundColor: "#f0f7ff" },
  radioCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#cbd5e0",
    marginRight: 12,
  },
  radioChecked: { borderColor: "#3b82f6", backgroundColor: "#3b82f6" },
  optionText: { fontSize: 16, color: "#475569" },

  // Botões
  primaryBtn: {
    backgroundColor: "#3b82f6",
    padding: 18,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 10,
  },
  primaryBtnText: { color: "#fff", fontWeight: "700", fontSize: 16 },
  btnDisabled: { backgroundColor: "#cbd5e0" },
  resultBtn: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    padding: 18,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    marginTop: 10,
    gap: 8,
  },
  resultBtnText: { color: "#3b82f6", fontWeight: "700" },

  // Resultado Final (Corrigindo os erros da imagem)
  finalResult: { alignItems: "center" },
  labelHeader: { color: "#64748b", marginBottom: 10, textAlign: "center" },
  bigLetter: {
    fontSize: 90,
    fontWeight: "900",
    color: "#3b82f6",
    textAlign: "center",
  },
  statusBox: { width: "100%", marginVertical: 20, alignItems: "center" },
  statusTitle: { fontSize: 14, color: "#64748b", marginBottom: 15 },
  letterCircles: { flexDirection: "row", gap: 12 },
  circle: {
    width: 45,
    height: 45,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  circleCorrect: { backgroundColor: "#bbf7d0", borderColor: "#22c55e" },
  circleWrong: { backgroundColor: "#fecaca", borderColor: "#ef4444" },
  circleText: { fontWeight: "700", color: "#64748b" },

  // Acordeões
  accordion: {
    width: "100%",
    backgroundColor: "#f1f5f9",
    padding: 16,
    borderRadius: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
    alignItems: "center",
  },
  accordionText: { fontWeight: "600", color: "#1e40af" },
  accordionContent: {
    width: "100%",
    padding: 20,
    backgroundColor: "#f8fafc",
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    marginTop: -5,
  },
  contentText: {
    fontSize: 15,
    color: "#475569",
    textAlign: "center",
    lineHeight: 22,
  },
  linkText: {
    color: "#3b82f6",
    textDecorationLine: "underline",
    textAlign: "center",
    marginTop: 10,
  },

  // Feedback
  feedbackSection: { width: "100%", marginVertical: 25 },
  feedbackTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: "#3b82f6",
    marginBottom: 8,
  },
  feedbackBody: { fontSize: 15, color: "#475569", lineHeight: 22 },

  tryAgainBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 15,
    padding: 16,
    borderWidth: 2,
    borderColor: "#3b82f6",
    borderRadius: 12,
    width: "100%",
  },
  tryAgainText: { color: "#3b82f6", fontWeight: "700" },
  rotateIcon: { transform: [{ rotate: "90deg" }] },
});
